import { PropsWithChildren } from 'react';

import './global.css';

export const metadata = {
  title: 'Welcome',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
