import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const universityTable = sqliteTable('universities', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  description: text('description'),
  logo: text('logo'),
  city: text('city'),
  state: text('state'),
  website: text('website'),
  qsrank: integer('qsrank'),
  bestField: text('best_field'),
  control: text('control', { enum: ['PUBLIC', 'PRIVATE', 'OTHER'] }),
  size: integer('size'),
  sex: text('sex', { enum: ['COED', 'MEN', 'WOMEN', 'OTHER'] }),
  primaryFocus: text('primary_focus'),
  religion: integer('religion', { mode: 'boolean' }),
  totalCost: real('total_cost'),
  coa: text('coa'),
  aidInternational: text('aid_international', {
    enum: ['YES', 'NO', 'LIMITED', 'UNKNOWN'],
  }),
  numberAidInt: integer('number_aid_int'),
  percentAidInt: real('percent_aid_int'),
  averageAmountAid: real('average_amount_aid'),
  costAfterAid: real('cost_after_aid'),
  maxAid: real('max_aid'),
  maxAidName: text('max_aid_name'),
  howToApply: text('how_to_apply'),
  note: text('note'),
  acceptanceRate: real('acceptance_rate'),
  rdAcceptance: real('rd_acceptance'),
  rdDeadline: text('rd_deadline'),
  edAcceptance: real('ed_acceptance'),
  edDeadline: text('ed_deadline'),
  eaAcceptance: real('ea_acceptance'),
  eaDeadline: text('ea_deadline'),
  percentSat: real('percent_sat'),
  averageSatScore: real('average_sat_score'),
  percentAct: real('percent_act'),
  fourYearGraduationRate: real('four_year_graduation_rate'),
  fiveYearGraduationRate: real('five_year_graduation_rate'),
  sixYearGraduationRate: real('six_year_graduation_rate'),
  eaEdFinancialAidDeadline: text('ea_ed_financial_aid_deadline'),
  ed2ApplicationDeadline: text('ed2_application_deadline'),
  ed2FinancialAidDeadline: text('ed2_financial_aid_deadline'),
  rdDocumentDeadline: text('rd_document_deadline'),
  rdOnlyFinancialAidDeadline: text('rd_only_financial_aid_deadline'),
});
